//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace AdvisementSys
{
    public partial class Entities : ObjectContext
    {
        public const string ConnectionString = "name=Entities";
        public const string ContainerName = "Entities";
    
        #region Constructors
    
        public Entities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public Entities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public Entities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<applicationForReadmission> applicationForReadmissions
        {
            get { return _applicationForReadmissions  ?? (_applicationForReadmissions = CreateObjectSet<applicationForReadmission>("applicationForReadmissions")); }
        }
        private ObjectSet<applicationForReadmission> _applicationForReadmissions;
    
        public ObjectSet<applicationForTermOrCompleteProgramWithdrawal> applicationForTermOrCompleteProgramWithdrawals
        {
            get { return _applicationForTermOrCompleteProgramWithdrawals  ?? (_applicationForTermOrCompleteProgramWithdrawals = CreateObjectSet<applicationForTermOrCompleteProgramWithdrawal>("applicationForTermOrCompleteProgramWithdrawals")); }
        }
        private ObjectSet<applicationForTermOrCompleteProgramWithdrawal> _applicationForTermOrCompleteProgramWithdrawals;
    
        public ObjectSet<appointment> appointments
        {
            get { return _appointments  ?? (_appointments = CreateObjectSet<appointment>("appointments")); }
        }
        private ObjectSet<appointment> _appointments;
    
        public ObjectSet<campu> campus
        {
            get { return _campus  ?? (_campus = CreateObjectSet<campu>("campus")); }
        }
        private ObjectSet<campu> _campus;
    
        public ObjectSet<coordinator> coordinators
        {
            get { return _coordinators  ?? (_coordinators = CreateObjectSet<coordinator>("coordinators")); }
        }
        private ObjectSet<coordinator> _coordinators;
    
        public ObjectSet<course> courses
        {
            get { return _courses  ?? (_courses = CreateObjectSet<course>("courses")); }
        }
        private ObjectSet<course> _courses;
    
        public ObjectSet<designation> designations
        {
            get { return _designations  ?? (_designations = CreateObjectSet<designation>("designations")); }
        }
        private ObjectSet<designation> _designations;
    
        public ObjectSet<employee> employees
        {
            get { return _employees  ?? (_employees = CreateObjectSet<employee>("employees")); }
        }
        private ObjectSet<employee> _employees;
    
        public ObjectSet<faculty> faculties
        {
            get { return _faculties  ?? (_faculties = CreateObjectSet<faculty>("faculties")); }
        }
        private ObjectSet<faculty> _faculties;
    
        public ObjectSet<issue> issues
        {
            get { return _issues  ?? (_issues = CreateObjectSet<issue>("issues")); }
        }
        private ObjectSet<issue> _issues;
    
        public ObjectSet<location> locations
        {
            get { return _locations  ?? (_locations = CreateObjectSet<location>("locations")); }
        }
        private ObjectSet<location> _locations;
    
        public ObjectSet<note> notes
        {
            get { return _notes  ?? (_notes = CreateObjectSet<note>("notes")); }
        }
        private ObjectSet<note> _notes;
    
        public ObjectSet<part_timeAnd_orAdditionalCourseRegistrationForm> part_timeAnd_orAdditionalCourseRegistrationForm
        {
            get { return _part_timeAnd_orAdditionalCourseRegistrationForm  ?? (_part_timeAnd_orAdditionalCourseRegistrationForm = CreateObjectSet<part_timeAnd_orAdditionalCourseRegistrationForm>("part_timeAnd_orAdditionalCourseRegistrationForm")); }
        }
        private ObjectSet<part_timeAnd_orAdditionalCourseRegistrationForm> _part_timeAnd_orAdditionalCourseRegistrationForm;
    
        public ObjectSet<probationaryContractPlan> probationaryContractPlans
        {
            get { return _probationaryContractPlans  ?? (_probationaryContractPlans = CreateObjectSet<probationaryContractPlan>("probationaryContractPlans")); }
        }
        private ObjectSet<probationaryContractPlan> _probationaryContractPlans;
    
        public ObjectSet<professor> professors
        {
            get { return _professors  ?? (_professors = CreateObjectSet<professor>("professors")); }
        }
        private ObjectSet<professor> _professors;
    
        public ObjectSet<program> programs
        {
            get { return _programs  ?? (_programs = CreateObjectSet<program>("programs")); }
        }
        private ObjectSet<program> _programs;
    
        public ObjectSet<requestForLateEnrolment> requestForLateEnrolments
        {
            get { return _requestForLateEnrolments  ?? (_requestForLateEnrolments = CreateObjectSet<requestForLateEnrolment>("requestForLateEnrolments")); }
        }
        private ObjectSet<requestForLateEnrolment> _requestForLateEnrolments;
    
        public ObjectSet<requiredcourse> requiredcourses
        {
            get { return _requiredcourses  ?? (_requiredcourses = CreateObjectSet<requiredcourse>("requiredcourses")); }
        }
        private ObjectSet<requiredcourse> _requiredcourses;
    
        public ObjectSet<role> roles
        {
            get { return _roles  ?? (_roles = CreateObjectSet<role>("roles")); }
        }
        private ObjectSet<role> _roles;
    
        public ObjectSet<startdate> startdates
        {
            get { return _startdates  ?? (_startdates = CreateObjectSet<startdate>("startdates")); }
        }
        private ObjectSet<startdate> _startdates;
    
        public ObjectSet<student> students
        {
            get { return _students  ?? (_students = CreateObjectSet<student>("students")); }
        }
        private ObjectSet<student> _students;
    
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get { return _sysdiagrams  ?? (_sysdiagrams = CreateObjectSet<sysdiagram>("sysdiagrams")); }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion
    }
}
