//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace AdvisementSys.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(program))]
    [KnownType(typeof(coordinator))]
    [KnownType(typeof(employee))]
    [KnownType(typeof(professor))]
    public partial class faculty: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public string fname
        {
            get { return _fname; }
            set
            {
                if (_fname != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'fname' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _fname = value;
                    OnPropertyChanged("fname");
                }
            }
        }
        private string _fname;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<program> programs
        {
            get
            {
                if (_programs == null)
                {
                    _programs = new TrackableCollection<program>();
                    _programs.CollectionChanged += Fixupprograms;
                }
                return _programs;
            }
            set
            {
                if (!ReferenceEquals(_programs, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_programs != null)
                    {
                        _programs.CollectionChanged -= Fixupprograms;
                    }
                    _programs = value;
                    if (_programs != null)
                    {
                        _programs.CollectionChanged += Fixupprograms;
                    }
                    OnNavigationPropertyChanged("programs");
                }
            }
        }
        private TrackableCollection<program> _programs;
    
        [DataMember]
        public TrackableCollection<coordinator> coordinators
        {
            get
            {
                if (_coordinators == null)
                {
                    _coordinators = new TrackableCollection<coordinator>();
                    _coordinators.CollectionChanged += Fixupcoordinators;
                }
                return _coordinators;
            }
            set
            {
                if (!ReferenceEquals(_coordinators, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_coordinators != null)
                    {
                        _coordinators.CollectionChanged -= Fixupcoordinators;
                    }
                    _coordinators = value;
                    if (_coordinators != null)
                    {
                        _coordinators.CollectionChanged += Fixupcoordinators;
                    }
                    OnNavigationPropertyChanged("coordinators");
                }
            }
        }
        private TrackableCollection<coordinator> _coordinators;
    
        [DataMember]
        public TrackableCollection<employee> employees
        {
            get
            {
                if (_employees == null)
                {
                    _employees = new TrackableCollection<employee>();
                    _employees.CollectionChanged += Fixupemployees;
                }
                return _employees;
            }
            set
            {
                if (!ReferenceEquals(_employees, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_employees != null)
                    {
                        _employees.CollectionChanged -= Fixupemployees;
                    }
                    _employees = value;
                    if (_employees != null)
                    {
                        _employees.CollectionChanged += Fixupemployees;
                    }
                    OnNavigationPropertyChanged("employees");
                }
            }
        }
        private TrackableCollection<employee> _employees;
    
        [DataMember]
        public TrackableCollection<professor> professors
        {
            get
            {
                if (_professors == null)
                {
                    _professors = new TrackableCollection<professor>();
                    _professors.CollectionChanged += Fixupprofessors;
                }
                return _professors;
            }
            set
            {
                if (!ReferenceEquals(_professors, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_professors != null)
                    {
                        _professors.CollectionChanged -= Fixupprofessors;
                    }
                    _professors = value;
                    if (_professors != null)
                    {
                        _professors.CollectionChanged += Fixupprofessors;
                    }
                    OnNavigationPropertyChanged("professors");
                }
            }
        }
        private TrackableCollection<professor> _professors;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            programs.Clear();
            coordinators.Clear();
            employees.Clear();
            professors.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void Fixupprograms(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (program item in e.NewItems)
                {
                    item.faculty1 = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("programs", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (program item in e.OldItems)
                {
                    if (ReferenceEquals(item.faculty1, this))
                    {
                        item.faculty1 = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("programs", item);
                    }
                }
            }
        }
    
        private void Fixupcoordinators(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (coordinator item in e.NewItems)
                {
                    item.faculty1 = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("coordinators", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (coordinator item in e.OldItems)
                {
                    if (ReferenceEquals(item.faculty1, this))
                    {
                        item.faculty1 = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("coordinators", item);
                    }
                }
            }
        }
    
        private void Fixupemployees(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (employee item in e.NewItems)
                {
                    item.faculty1 = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("employees", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (employee item in e.OldItems)
                {
                    if (ReferenceEquals(item.faculty1, this))
                    {
                        item.faculty1 = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("employees", item);
                    }
                }
            }
        }
    
        private void Fixupprofessors(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (professor item in e.NewItems)
                {
                    item.faculty1 = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("professors", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (professor item in e.OldItems)
                {
                    if (ReferenceEquals(item.faculty1, this))
                    {
                        item.faculty1 = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("professors", item);
                    }
                }
            }
        }

        #endregion
    }
}
